# Fork of Visual Studio style from ImThemes
alpha = 1.0
disabledAlpha = 0.449999988079071
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [6.0, 4.5]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [6.0, 4.0]
itemInnerSpacing = [6.0, 6.0]
cellPadding = [4.0, 6.0]
indentSpacing = 16.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 0.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 0.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(151, 151, 151, 1.0)"
WindowBg = "rgba(37, 37, 38, 1.0)"
ChildBg = "rgba(37, 37, 38, 1.0)"
PopupBg = "rgba(37, 37, 38, 1.0)"
Border = "rgba(78, 78, 78, 1.0)"
BorderShadow = "rgba(78, 78, 78, 1.0)"
FrameBg = "rgba(51, 51, 55, 1.0)"
FrameBgHovered = "rgba(29, 151, 236, 1.0)"
FrameBgActive = "rgba(0, 119, 200, 1.0)"
TitleBg = "rgba(37, 37, 38, 1.0)"
TitleBgActive = "rgba(37, 37, 38, 1.0)"
TitleBgCollapsed = "rgba(37, 37, 38, 1.0)"
MenuBarBg = "rgba(51, 51, 55, 1.0)"
ScrollbarBg = "rgba(51, 51, 55, 1.0)"
ScrollbarGrab = "rgba(82, 82, 85, 1.0)"
ScrollbarGrabHovered = "rgba(90, 90, 95, 1.0)"
ScrollbarGrabActive = "rgba(90, 90, 95, 1.0)"
CheckMark = "rgba(0, 119, 200, 1.0)"
SliderGrab = "rgba(29, 151, 236, 1.0)"
SliderGrabActive = "rgba(0, 119, 200, 1.0)"
Button = "rgba(51, 51, 55, 1.0)"
ButtonHovered = "rgba(29, 151, 236, 1.0)"
ButtonActive = "rgba(29, 151, 236, 1.0)"
Header = "rgba(51, 51, 55, 1.0)"
HeaderHovered = "rgba(29, 151, 236, 1.0)"
HeaderActive = "rgba(0, 119, 200, 1.0)"
Separator = "rgba(78, 78, 78, 1.0)"
SeparatorHovered = "rgba(78, 78, 78, 1.0)"
SeparatorActive = "rgba(78, 78, 78, 1.0)"
ResizeGrip = "rgba(37, 37, 38, 1.0)"
ResizeGripHovered = "rgba(51, 51, 55, 1.0)"
ResizeGripActive = "rgba(82, 82, 85, 1.0)"
Tab = "rgba(37, 37, 38, 1.0)"
TabHovered = "rgba(29, 151, 236, 1.0)"
TabActive = "rgba(0, 119, 200, 1.0)"
TabUnfocused = "rgba(37, 37, 38, 1.0)"
TabUnfocusedActive = "rgba(0, 119, 200, 1.0)"
PlotLines = "rgba(0, 119, 200, 1.0)"
PlotLinesHovered = "rgba(29, 151, 236, 1.0)"
PlotHistogram = "rgba(0, 119, 200, 1.0)"
PlotHistogramHovered = "rgba(29, 151, 236, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.05999999865889549)"
TextSelectedBg = "rgba(0, 119, 200, 1.0)"
DragDropTarget = "rgba(37, 37, 38, 1.0)"
NavHighlight = "rgba(37, 37, 38, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.699999988079071)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2000000029802322)"
ModalWindowDimBg = "rgba(37, 37, 38, 1.0)"
